name: Workflow local

on: [push, workflow_dispatch]

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Simulation d’exécution du Build
        run: echo "Build en cours"

  deployJob:
    runs-on: ubuntu-latest
    needs: buildJob
    steps:
      - name: Déploiement sur Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "NOM_DE_VOTRE_APPLICATION"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
