name: Workflow local

on: [push, workflow_dispatch]

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build de l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app-devops:latest .

      - name: Login à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push de l’image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app-devops:latest
